from src.llm.model import PromptOutput


class FormatterWriterService[O: PromptOutput]:
    """
    Service responsible for saving formatted LLM outputs to a file.

    The service takes the generated output and writes its text content
    to a file in the specified format.
    """

    def save(self, output: O, data_format: str, filename: str | None = None) -> str:
        """
        Save the formatted output to a file.

        Parameters
        ----------
        output : O
            The output object containing the text generated by the model.
        data_format : str
            File format/extension used for the output file (e.g., "txt", "md", "json").
        filename : str | None, optional
            Custom name for the output file. If not provided, a default
            name `summary_output.<format>` will be used.

        Returns
        -------
        str
            The path to the saved file.
        """
        path = filename or f"summary_output.{data_format}"
        with open(path, "w", encoding="utf-8") as file:
            file.write(output.text)
        return path